import Head from "next/head";
import Image from "next/image";
import useSWR from "swr";

import styles from "../styles/Home.module.css";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

// @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
const dateFormat = (dateString) => {
  const date = new Date(dateString);
  return date.toLocaleDateString("id-ID", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
};

export default function Home() {
  const { data, error } = useSWR(`/api/db`, fetcher);

  if (error) return <div>{`Ooops... error`}</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {data?.map((database) => (
            <a key={database.id} href={`/event/${database.id}`} className={styles.card}>
              <div>
                {database?.properties?.EventCategory?.multi_select?.map((tags) => (
                  <span key={tags.id}>{`#${tags?.name} `}</span>
                ))}
              </div>
              <p className={styles.date}>{`${dateFormat(
                database?.properties?.EventDate?.date?.start
              )} - ${dateFormat(database?.properties?.EventDate?.date?.end)}`}</p>
              <h2>{database?.properties?.EventName?.title[0].text?.content}</h2>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
